var MENU_DATA = [
  {
    "_id": "item-001",
    "name": "Stacked Pancakes (Berry & Caramelized Banana)",
    "category": "Breakfast",
    "categorySlug": "breakfast",
    "price": 320,
    "description": "Fluffy, golden pancakes with juicy homemade mixed berries jam, caramelized banana, and a drizzle of rich maple syrup.",
    "dietaryType": "veg",
    "prepTimeMinutes": 10,
    "tags": [],
    "rating": { "average": 5.0, "count": 61 },
    "imageUrl": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-002",
    "name": "All Day Breakfast",
    "category": "Breakfast",
    "categorySlug": "breakfast",
    "price": 380,
    "description": "Artisan toast, sautéed mushrooms and cherry tomatoes, sliced avocado and choice of your egg served with achari hollandaise on the side.",
    "dietaryType": "egg",
    "prepTimeMinutes": 10,
    "tags": ["bestseller"],
    "rating": { "average": 4.7, "count": 116 },
    "imageUrl": "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-003",
    "name": "Eggs On Avocado W Achari Hollandaise",
    "category": "Breakfast",
    "categorySlug": "breakfast",
    "price": 295,
    "description": "Creamy smashed avocado spread over crisp sourdough bread, topped with two perfectly cooked eggs of your choice, finished with our signature achari hollandaise.",
    "dietaryType": "egg",
    "prepTimeMinutes": 10,
    "tags": ["bestseller"],
    "rating": { "average": 4.1, "count": 89 },
    "imageUrl": "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-004",
    "name": "Honey Butter Toast",
    "category": "Breakfast",
    "categorySlug": "breakfast",
    "price": 285,
    "description": "Golden brioche soaked in vanilla custard, topped with honey-butter and a cloud of clotted cream — sweet mornings in every bite.",
    "dietaryType": "veg",
    "prepTimeMinutes": 10,
    "tags": ["bestseller"],
    "rating": { "average": 4.5, "count": 44 },
    "imageUrl": "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-005",
    "name": "Hummus & Pickled Veg",
    "category": "Bagels",
    "categorySlug": "bagels",
    "price": 285,
    "description": "A toasty bagel spread with creamy hummus, pickled veggies and crisp lettuce, olive oil. Bright, savory, and satisfying.",
    "dietaryType": "veg",
    "prepTimeMinutes": 8,
    "tags": [],
    "rating": { "average": 4.2, "count": 38 },
    "imageUrl": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-006",
    "name": "3 Cheese & Caramelized Onions",
    "category": "Bagels",
    "categorySlug": "bagels",
    "price": 310,
    "description": "A toasty bagel with cream cheese, shredded cheddar and mozzarella, then crowned with sweet caramelized onion chutney & fresh arugula.",
    "dietaryType": "veg",
    "prepTimeMinutes": 8,
    "tags": ["chefs-special"],
    "rating": { "average": 4.6, "count": 52 },
    "imageUrl": "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-007",
    "name": "Pizza Bagel",
    "category": "Bagels",
    "categorySlug": "bagels",
    "price": 340,
    "description": "A toasty bagel with herb-garlic butter, topped with rich marinara sauce, melted mozzarella, and chicken pepperoni slices.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 10,
    "tags": ["bestseller"],
    "rating": { "average": 4.8, "count": 74 },
    "imageUrl": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-008",
    "name": "Watermelon Feta",
    "category": "Salads",
    "categorySlug": "salads",
    "price": 175,
    "description": "A fresh & light salad with juicy fresh watermelon with feta over arugula and mint leaves. Dressed in a balsamic vinaigrette.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": ["new"],
    "rating": { "average": 4.3, "count": 29 },
    "imageUrl": "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-009",
    "name": "Iron Feast",
    "category": "Salads",
    "categorySlug": "salads",
    "price": 220,
    "description": "A hearty bowl of greens with iceberg, baby spinach, quinoa, lentils, cherry tomatoes, orange, pumpkin & sunflower seeds, feta and orange vinaigrette.",
    "dietaryType": "veg",
    "prepTimeMinutes": 8,
    "tags": ["chefs-special"],
    "rating": { "average": 4.4, "count": 35 },
    "imageUrl": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-010",
    "name": "Buffalo Chicken",
    "category": "Pide",
    "categorySlug": "pide",
    "price": 350,
    "description": "A crisp boat-shaped pide base piled high with juicy chicken tossed in tangy, spicy buffalo sauce. Topped with mozzarella cheese.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 15,
    "tags": ["bestseller"],
    "rating": { "average": 4.7, "count": 88 },
    "imageUrl": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-011",
    "name": "Creamed Corn & Spinach",
    "category": "Pide",
    "categorySlug": "pide",
    "price": 295,
    "description": "Golden pide filled with sweet corn, baby spinach, creamy sauce, and a cheesy-garlic finish.",
    "dietaryType": "veg",
    "prepTimeMinutes": 15,
    "tags": [],
    "rating": { "average": 4.1, "count": 42 },
    "imageUrl": "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-012",
    "name": "Thecha Shrimp",
    "category": "Pide",
    "categorySlug": "pide",
    "price": 375,
    "description": "Shrimp sautéed in fiery thecha — a rustic Maharashtrian chili-&-nut spice mix — with roasted garlic, fresh herbs, and mozzarella.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 15,
    "tags": ["chefs-special"],
    "spiceLevel": "hot",
    "rating": { "average": 4.5, "count": 31 },
    "imageUrl": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-013",
    "name": "Buffalo Chicken Crostini",
    "category": "Crostini",
    "categorySlug": "crostini",
    "price": 330,
    "description": "A warm garlic-herb butter brushed baguette layered with sour cream, fiery buffalo-tossed chicken, tangy feta. Spicy, mellow, and satisfying.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 10,
    "tags": [],
    "spiceLevel": "medium",
    "rating": { "average": 4.3, "count": 47 },
    "imageUrl": "https://images.unsplash.com/photo-1432139509613-5c4255a1d916?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-014",
    "name": "Mediterranean",
    "category": "Crostini",
    "categorySlug": "crostini",
    "price": 250,
    "description": "A warm garlic-herb butter brushed baguette, topped with homemade hummus, crumbly feta, and grilled veggies.",
    "dietaryType": "veg",
    "prepTimeMinutes": 8,
    "tags": [],
    "rating": { "average": 4.0, "count": 33 },
    "imageUrl": "https://images.unsplash.com/photo-1505576399279-0d79dfa27d63?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-015",
    "name": "Avocado & Sundried Tomato",
    "category": "Crostini",
    "categorySlug": "crostini",
    "price": 275,
    "description": "Soft smashed avocado over herb garlic butter, with sun-dried tomatoes and crunchy roasted almonds, a sweet-heat drizzle of chili-infused honey.",
    "dietaryType": "veg",
    "prepTimeMinutes": 8,
    "tags": ["new"],
    "rating": { "average": 4.4, "count": 28 },
    "imageUrl": "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-016",
    "name": "Toscano Dolce",
    "category": "Dessert",
    "categorySlug": "dessert",
    "price": 345,
    "description": "Soft vanilla cake gently soaked in a rich coffee elixir, coffee cream — a perfect twist on classic tiramisu.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": ["chefs-special", "bestseller"],
    "rating": { "average": 4.9, "count": 97 },
    "imageUrl": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-017",
    "name": "Isle Of Lime",
    "category": "Dessert",
    "categorySlug": "dessert",
    "price": 250,
    "description": "A refreshing tropical indulgence with biscoff crumble, lime & coconut cream cheese, coconut sauce, and a hint of mint.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": ["new"],
    "rating": { "average": 4.2, "count": 22 },
    "imageUrl": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-018",
    "name": "Yam Chips",
    "category": "Nibbles",
    "categorySlug": "nibbles",
    "price": 115,
    "description": "A twist your taste buds won't see coming — thinly hand cut elephant foot yam, fried and seasoned with homemade secret spiced mix.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": [],
    "rating": { "average": 4.0, "count": 56 },
    "imageUrl": "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-019",
    "name": "Tendli Fries",
    "category": "Nibbles",
    "categorySlug": "nibbles",
    "price": 115,
    "description": "Your new favourite sidekick to any meal — spiced ivy gourd seasoned with homemade secret spice mix, fried to golden perfection.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": [],
    "rating": { "average": 4.1, "count": 41 },
    "imageUrl": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-020",
    "name": "Ham & Cheese",
    "category": "Sandwiches",
    "categorySlug": "sandwiches",
    "price": 425,
    "description": "Mustard, cheddar cheese, tomato, caramelized onion and chicken ham, fried egg on sourdough bread.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 10,
    "tags": ["bestseller"],
    "rating": { "average": 4.6, "count": 63 },
    "imageUrl": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-021",
    "name": "Roasted Veg",
    "category": "Sandwiches",
    "categorySlug": "sandwiches",
    "price": 340,
    "description": "Sourdough bread, pesto, hummus, grilled veg, feta cheese, tomato and lettuce.",
    "dietaryType": "veg",
    "prepTimeMinutes": 10,
    "tags": [],
    "rating": { "average": 4.2, "count": 37 },
    "imageUrl": "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-022",
    "name": "BBQ Chicken Sandwich",
    "category": "Sandwiches",
    "categorySlug": "sandwiches",
    "price": 380,
    "description": "BBQ mayo, lettuce, gherkins, BBQ chicken, cheddar cheese, fried egg.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 10,
    "tags": [],
    "rating": { "average": 4.4, "count": 55 },
    "imageUrl": "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-023",
    "name": "Egg Avocado And Bacon Sandwich",
    "category": "Sandwiches",
    "categorySlug": "sandwiches",
    "price": 360,
    "description": "Churmuri mayo, cheese, roman lettuce, chicken bacon, avocado, fried egg on sourdough bread.",
    "dietaryType": "non-veg",
    "prepTimeMinutes": 10,
    "tags": [],
    "rating": { "average": 4.3, "count": 48 },
    "imageUrl": "https://images.unsplash.com/photo-1550507992-eb63ffee0847?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-024",
    "name": "Espresso",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 160,
    "description": "Concentrated coffee, pure, rich, hot.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.5, "count": 120 },
    "imageUrl": "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-025",
    "name": "Double Espresso",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 190,
    "description": "Concentrated coffee, pure, rich, hot — double the intensity.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.4, "count": 85 },
    "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-026",
    "name": "Americano",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 175,
    "description": "Smooth espresso diluted with hot water for a mellow cup.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.2, "count": 92 },
    "imageUrl": "https://images.unsplash.com/photo-1521302080334-4bebac2763a6?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-027",
    "name": "Cappuccino",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 190,
    "description": "Espresso crowned with velvety steamed milk and foam.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["bestseller"],
    "rating": { "average": 4.7, "count": 145 },
    "imageUrl": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-028",
    "name": "Caffè Latte",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 190,
    "description": "Creamy steamed milk blended with a bold espresso base.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.5, "count": 110 },
    "imageUrl": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-029",
    "name": "Flat White",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 190,
    "description": "Silky micro-foam and espresso in perfect balance.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.3, "count": 78 },
    "imageUrl": "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-030",
    "name": "Mocha",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 220,
    "description": "Espresso with steamed milk and a touch of chocolate indulgence.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": [],
    "rating": { "average": 4.4, "count": 67 },
    "imageUrl": "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-031",
    "name": "Cortado",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 200,
    "description": "Equal parts espresso and warm milk for a smooth, bold sip.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.1, "count": 54 },
    "imageUrl": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-032",
    "name": "Hot Chocolate Premium",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 230,
    "description": "Luxurious cocoa finished with steamed milk.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": [],
    "rating": { "average": 4.6, "count": 73 },
    "imageUrl": "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-033",
    "name": "Spanish Latte",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 230,
    "description": "Espresso sweetened with condensed milk and velvety foam.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["bestseller"],
    "rating": { "average": 4.8, "count": 91 },
    "imageUrl": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-034",
    "name": "Macchiato",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 200,
    "description": "Espresso \"stained\" with a dollop of frothy milk.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.2, "count": 48 },
    "imageUrl": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-035",
    "name": "Hot Tea",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 230,
    "description": "A selection of fine teas, including black, green, and herbal.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": [],
    "rating": { "average": 4.0, "count": 39 },
    "imageUrl": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-036",
    "name": "Iced Americano",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 190,
    "description": "Espresso poured over cold water and ice for a crisp finish.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.3, "count": 88 },
    "imageUrl": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-037",
    "name": "Classic Iced Coffee",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 220,
    "description": "Robust coffee with vanilla ice cream blended with ice.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["bestseller"],
    "rating": { "average": 4.6, "count": 102 },
    "imageUrl": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-038",
    "name": "Iced Latte",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 220,
    "description": "Cold milk and espresso served refreshingly over ice.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.4, "count": 95 },
    "imageUrl": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-039",
    "name": "Iced Mocha",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 250,
    "description": "Espresso, chocolate, and chilled milk on the rocks.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.5, "count": 69 },
    "imageUrl": "https://images.unsplash.com/photo-1592663527359-cf6642f54cff?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-040",
    "name": "Caramel Iced Coffee",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 260,
    "description": "Classic iced coffee with a rich caramel drizzle.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.5, "count": 58 },
    "imageUrl": "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-041",
    "name": "Nordic Spark",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 280,
    "description": "Espresso & tonic water — a refreshing fizzy coffee experience.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": ["chefs-special"],
    "rating": { "average": 4.2, "count": 34 },
    "imageUrl": "https://images.unsplash.com/photo-1499961024556-64b8ddbb4e5e?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-042",
    "name": "Island Drift",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 280,
    "description": "Fresh coconut water & espresso — tropical meets bold.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": ["new"],
    "rating": { "average": 4.3, "count": 27 },
    "imageUrl": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-043",
    "name": "Mediterranean Glow",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 280,
    "description": "Orange, honey & espresso — bright and energizing.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["chefs-special"],
    "rating": { "average": 4.4, "count": 41 },
    "imageUrl": "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-044",
    "name": "Cold Brew With Milk",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 280,
    "description": "This delicious latte style cold brew has notes of dry fruit, shiraz and caramel.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.5, "count": 72 },
    "imageUrl": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-045",
    "name": "Vietnamese Style Iced Coffee",
    "category": "Iced Beverages",
    "categorySlug": "iced-beverages",
    "price": 280,
    "description": "Concentrated, dark cold brew poured over ice, topped with sweetened condensed milk.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["bestseller"],
    "rating": { "average": 4.7, "count": 83 },
    "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-046",
    "name": "Medium Roast Pour Over",
    "category": "Pour Over",
    "categorySlug": "pour-over",
    "price": 280,
    "description": "Rich chocolate caramel notes — handcrafted pour over.",
    "dietaryType": "veg",
    "prepTimeMinutes": 6,
    "tags": [],
    "rating": { "average": 4.3, "count": 38 },
    "imageUrl": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-047",
    "name": "Medium Dark Pour Over",
    "category": "Pour Over",
    "categorySlug": "pour-over",
    "price": 290,
    "description": "Berry & chocolate with velvety finish — handcrafted pour over.",
    "dietaryType": "veg",
    "prepTimeMinutes": 6,
    "tags": ["chefs-special"],
    "rating": { "average": 4.4, "count": 29 },
    "imageUrl": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-048",
    "name": "Mild Pour Over",
    "category": "Pour Over",
    "categorySlug": "pour-over",
    "price": 290,
    "description": "Banana and berry — light and delicate handcrafted pour over.",
    "dietaryType": "veg",
    "prepTimeMinutes": 6,
    "tags": [],
    "rating": { "average": 4.1, "count": 22 },
    "imageUrl": "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-049",
    "name": "Watermelon Juice",
    "category": "Coolers",
    "categorySlug": "coolers",
    "price": 120,
    "description": "Fresh pressed watermelon juice — pure and refreshing.",
    "dietaryType": "veg",
    "prepTimeMinutes": 3,
    "tags": [],
    "rating": { "average": 4.2, "count": 45 },
    "imageUrl": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-050",
    "name": "Lemon Mint Mojito",
    "category": "Coolers",
    "categorySlug": "coolers",
    "price": 150,
    "description": "Zesty lemon and fresh mint — a classic thirst quencher.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["bestseller"],
    "rating": { "average": 4.5, "count": 78 },
    "imageUrl": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-051",
    "name": "Orange Mint Mojito",
    "category": "Coolers",
    "categorySlug": "coolers",
    "price": 150,
    "description": "Sweet orange meets fresh mint — citrusy and vibrant.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.3, "count": 52 },
    "imageUrl": "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-052",
    "name": "Green Apple Mojito",
    "category": "Coolers",
    "categorySlug": "coolers",
    "price": 150,
    "description": "Crisp green apple with lime and mint — tangy and refreshing.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.1, "count": 36 },
    "imageUrl": "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-053",
    "name": "Lemon Fresh Soda",
    "category": "Coolers",
    "categorySlug": "coolers",
    "price": 110,
    "description": "Sparkling fresh lemon soda — simple and effervescent.",
    "dietaryType": "veg",
    "prepTimeMinutes": 2,
    "tags": [],
    "rating": { "average": 3.9, "count": 41 },
    "imageUrl": "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-054",
    "name": "Strawberry Milkshake",
    "category": "Milkshakes",
    "categorySlug": "milkshakes",
    "price": 165,
    "description": "Creamy strawberry milkshake blended to smooth perfection.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.4, "count": 62 },
    "imageUrl": "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-055",
    "name": "Berry Blast Milkshake",
    "category": "Milkshakes",
    "categorySlug": "milkshakes",
    "price": 165,
    "description": "A burst of mixed berries blended with creamy milk and ice.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.3, "count": 47 },
    "imageUrl": "https://images.unsplash.com/photo-1553787499-6f9133860278?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-056",
    "name": "Vanilla Milkshake",
    "category": "Milkshakes",
    "categorySlug": "milkshakes",
    "price": 165,
    "description": "Classic vanilla milkshake — timeless and smooth.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": [],
    "rating": { "average": 4.2, "count": 39 },
    "imageUrl": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-057",
    "name": "Mango Milkshake",
    "category": "Milkshakes",
    "categorySlug": "milkshakes",
    "price": 165,
    "description": "Tropical mango blended into a rich, creamy shake.",
    "dietaryType": "veg",
    "prepTimeMinutes": 4,
    "tags": ["bestseller"],
    "rating": { "average": 4.6, "count": 71 },
    "imageUrl": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-058",
    "name": "Ocean Iced Latte",
    "category": "Specialty Coffees",
    "categorySlug": "specialty-coffees",
    "price": 350,
    "description": "Layers of silky caramel syrup, aromatic butterfly pea tea, rich espresso, and warm milk, topped with a soft cloud of milk foam.",
    "dietaryType": "veg",
    "prepTimeMinutes": 6,
    "tags": ["chefs-special", "new"],
    "rating": { "average": 4.8, "count": 56 },
    "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-059",
    "name": "Mediterranean Glow Iced Latte",
    "category": "Specialty Coffees",
    "categorySlug": "specialty-coffees",
    "price": 220,
    "description": "Sweet honey forms the base, followed by a burst of fresh orange juice, finished with a rich layer of espresso.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": ["new"],
    "rating": { "average": 4.5, "count": 43 },
    "imageUrl": "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=800&h=600&fit=crop"
  },
  {
    "_id": "item-060",
    "name": "S'mores Hot Chocolate",
    "category": "Hot Beverage",
    "categorySlug": "hot-beverage",
    "price": 250,
    "description": "A decadent hot chocolate topped with torched marshmallow for that classic campfire s'mores flavour.",
    "dietaryType": "veg",
    "prepTimeMinutes": 5,
    "tags": ["chefs-special"],
    "rating": { "average": 4.7, "count": 64 },
    "imageUrl": "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800&h=600&fit=crop"
  }
];
